use crate::domain::{
    AmendCommitCreated, AmendCommitInput, AmendCommitPreview, BranchCreateAtCommitInput,
    BranchInfo, BranchKind, BranchStatus, ChangeKind, CherryPickCommitInput,
    CherryPickCommitPreview, CloneOperationStarted, CommitCreated, CommitDetails, CommitFileChange,
    CommitInput, CommitSummary, ConflictDetails, ConflictResolutionChoice, ConflictResolutionInput,
    ConflictSide, FileChange, GitOperationEvent, GitOperationKind, GitOperationStarted,
    GitOperationState, GitVersion, HistoryPage, HistoryQuery, ImageDiff, ImagePreview,
    LocalMergeMode, LocalMergePreview, LocalMergeStrategy, MergeRecoveryInput,
    MergeRecoveryPreview, Project, ProjectMetadataUpdateInput, PublishBranchInput,
    RemoteCreateInput, RemoteDeleteInput, RemoteDeletePreview, RemoteEditPreview, RemoteInfo,
    RemoteTagDeleteInput, RemoteTagDeletePreview, RemoteTagDeletePreviewInput, RemoteTagPushInput,
    RemoteUpdateInput, RepositoryMutationResult, RepositoryRefs, RepositoryRefsMutationResult,
    RepositoryStashes, RepositoryStashesMutationResult, RepositoryStatus, RepositorySubmodules,
    RepositoryTags, RepositoryTagsMutationResult, RepositoryWorktrees, ResetCommitInput,
    ResetCommitMode, ResetCommitPreview, RevertCommitInput, RevertCommitPreview, StashCreateInput,
    StashInfo, SubmoduleInfo, SubmoduleState, TagInfo, UpdateCheckResult, UpdateProgressEvent,
    WorktreeCreateCandidate, WorktreeCreateInput, WorktreeDiff, WorktreeInfo, WorktreeLockInput,
    WorktreePruneInput, WorktreeUnlockInput,
};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use ts_rs::{Config, TS};

const GENERATED_HEADER: &str =
    "// @generated by `pnpm run generate:bindings`; do not edit by hand.\n\n";

fn generated_bindings() -> String {
    let mut output = String::from(GENERATED_HEADER);
    let config = Config::default();

    macro_rules! declare {
        ($type:ty) => {{
            writeln!(output, "export {}", <$type as TS>::decl(&config))
                .expect("writing to String cannot fail");
            output.push('\n');
        }};
    }

    // Keep this list alphabetical. TypeScript declarations may reference types
    // declared later in the same module, so dependency order is unnecessary.
    declare!(AmendCommitCreated);
    declare!(AmendCommitInput);
    declare!(AmendCommitPreview);
    declare!(BranchCreateAtCommitInput);
    declare!(BranchInfo);
    declare!(BranchKind);
    declare!(BranchStatus);
    declare!(ChangeKind);
    declare!(CherryPickCommitInput);
    declare!(CherryPickCommitPreview);
    declare!(CloneOperationStarted);
    declare!(CommitCreated);
    declare!(CommitDetails);
    declare!(CommitFileChange);
    declare!(CommitInput);
    declare!(CommitSummary);
    declare!(ConflictDetails);
    declare!(ConflictResolutionChoice);
    declare!(ConflictResolutionInput);
    declare!(ConflictSide);
    declare!(FileChange);
    declare!(GitOperationEvent);
    declare!(GitOperationKind);
    declare!(GitOperationStarted);
    declare!(GitOperationState);
    declare!(GitVersion);
    declare!(HistoryPage);
    declare!(HistoryQuery);
    declare!(ImageDiff);
    declare!(ImagePreview);
    declare!(LocalMergeMode);
    declare!(LocalMergePreview);
    declare!(LocalMergeStrategy);
    declare!(MergeRecoveryInput);
    declare!(MergeRecoveryPreview);
    declare!(Project);
    declare!(ProjectMetadataUpdateInput);
    declare!(PublishBranchInput);
    declare!(RemoteCreateInput);
    declare!(RemoteDeleteInput);
    declare!(RemoteDeletePreview);
    declare!(RemoteEditPreview);
    declare!(RemoteInfo);
    declare!(RemoteTagDeleteInput);
    declare!(RemoteTagDeletePreview);
    declare!(RemoteTagDeletePreviewInput);
    declare!(RemoteTagPushInput);
    declare!(RemoteUpdateInput);
    declare!(RepositoryMutationResult);
    declare!(RepositoryRefs);
    declare!(RepositoryRefsMutationResult);
    declare!(RepositoryStashes);
    declare!(RepositoryStashesMutationResult);
    declare!(RepositoryStatus);
    declare!(RepositorySubmodules);
    declare!(RepositoryTags);
    declare!(RepositoryTagsMutationResult);
    declare!(RepositoryWorktrees);
    declare!(ResetCommitInput);
    declare!(ResetCommitMode);
    declare!(ResetCommitPreview);
    declare!(RevertCommitInput);
    declare!(RevertCommitPreview);
    declare!(StashCreateInput);
    declare!(StashInfo);
    declare!(SubmoduleInfo);
    declare!(SubmoduleState);
    declare!(TagInfo);
    declare!(UpdateCheckResult);
    declare!(UpdateProgressEvent);
    declare!(WorktreeCreateCandidate);
    declare!(WorktreeCreateInput);
    declare!(WorktreeDiff);
    declare!(WorktreeInfo);
    declare!(WorktreeLockInput);
    declare!(WorktreePruneInput);
    declare!(WorktreeUnlockInput);

    output
}

fn bindings_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/platform/desktop/generated/domain.ts")
}

#[test]
fn generated_typescript_bindings_are_current() {
    let path = bindings_path();
    let actual = fs::read_to_string(&path).unwrap_or_else(|error| {
        panic!(
            "failed to read generated TypeScript bindings at {}: {error}; run `pnpm run generate:bindings`",
            path.display()
        )
    });
    let expected = generated_bindings();

    assert_eq!(
        actual, expected,
        "Rust DTOs and generated TypeScript bindings differ; run `pnpm run generate:bindings`"
    );
}

#[test]
#[ignore = "writes the checked-in TypeScript bindings"]
fn export_typescript_bindings() {
    let path = bindings_path();
    let parent = path.parent().expect("bindings path must have a parent");
    fs::create_dir_all(parent).expect("failed to create bindings directory");

    let generated = generated_bindings();
    if fs::read_to_string(&path).ok().as_deref() != Some(generated.as_str()) {
        fs::write(&path, generated).expect("failed to write generated bindings");
    }

    println!("generated {}", path.display());
}
